[workspace]
members = [
  "crates/async-dropper-derive",
  "crates/async-dropper"
]

[workspace.dependencies]
anyhow = "1.0.71"
thiserror = "1.0.40"
async-std = "1.12.0"
tokio = "1.29.1"
async-trait = "0.1.69"
proc-macro2 = "1.0.66"
quote = "1.0.32"
async-dropper-derive = { path = "crates/async-dropper-derive" }
async-dropper-simple = { path = "crates/async-dropper-simple" }
syn = "2.0.27"
futures = "0.3.28"