[workspace]
resolver = "2"
members = [
  "crates/async-dropper",
  "crates/async-dropper-derive",
  "crates/async-dropper-simple",
]

[workspace.dependencies]
async-std = "1.12.0"
tokio = "1.29.1"
async-trait = "0.1.69"
proc-macro2 = "1.0.66"
quote = "1.0.32"
syn = "2.0.27"
futures = "0.3.28"