[package]
name = "async-dropper"
version = "0.0.1"
repository = "https://github.com/t3hmrman/async-dropper"
license = "MIT"
readme = "README.md"
edition = "2021"
rust-version = "1.70"
authors = [
  "vados <vados@vadosware.io>",
]
categories = [
  "asynchronous",
]
description = """
The least-worst ad-hoc implementation of AsyncDrop as a Derive macro
"""

[[example]]
name = "async-drop-tokio"
path = "../../examples/async_drop_tokio.rs"
crate-type = [ "bin" ]
required-features = [ "tokio" ]

[[example]]
name = "async-drop-async-std"
path = "../../examples/async_drop_async_std.rs"
crate-type = [ "bin" ]
required-features = [ "async-std" ]

[[example]]
name = "async-drop-simple-tokio"
path = "../../examples/async_drop_simple_tokio.rs"
crate-type = [ "bin" ]
required-features = [ "tokio" ]

[[example]]
name = "async-drop-simple-async-std"
path = "../../examples/async_drop_simple_async_std.rs"
crate-type = [ "bin" ]
required-features = [ "async-std" ]

[features]
defaults = []
tokio = ["dep:tokio", "async-dropper-derive/tokio"]
async-std = ["dep:async-std", "async-dropper-derive/async-std"]

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
async-std = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = [ "rt", "rt-multi-thread" ] }
futures.workspace = true
async-trait.workspace = true
async-dropper-derive = { path = "../async-dropper-derive", version = "0.1.0" }
async-dropper-simple = { path = "../async-dropper-simple", version = "0.1.1" }

[dev-dependencies]
tokio = { workspace = true, features = [ "time", "macros", "rt", "rt-multi-thread" ]}
async-std = { workspace = true, features = [ "attributes" ]}
