[package]
name = "async-dropper"
version = "0.0.1"
repository = "https://github.com/t3hmrman/async-dropper"
license = "MIT"
readme = "README.md"
edition = "2021"
rust-version = "1.70"
authors = [
  "vados <vados@vadosware.io>",
]
categories = [
  "asynchronous",
]
description = """
The least-worst ad-hoc implementation of AsyncDrop as a Derive macro
"""

[[example]]
name = "async-drop"
path = "../../examples/async_drop.rs"
crate-type = [ "bin" ]
required-features = [ "tokio" ]

[features]
defaults = ["tokio"]
tokio = ["dep:tokio"]
async-std = ["dep:async-std"]

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
async-std = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
futures.workspace = true
async-trait.workspace = true
async-dropper-derive.workspace = true
async-dropper-simple.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = [ "time", "macros", "rt", "rt-multi-thread" ]}